server:
  port: 9000
spring:
  application:
    name: shop-web
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.129:8848
  thymeleaf:
    mode: LEGACYHTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
      #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 30000
        connectTimeout: 10000